version: '3.6'
services:
    postgres-patients:
        image: postgres:12
        restart: always
        ports:
            - '5432:5432'
        networks:
            - mynet
        environment:
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'mysecretpassword'
            POSTGRES_DB: 'patients_db'
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
            interval: 10s
            timeout: 5s
            retries: 5


    minio_server:
        image: minio/minio:latest
        restart: always
        command: minio server /data --console-address ":9001"
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            MINIO_ROOT_USER: 'minioadmin'
            MINIO_ROOT_PASSWORD: 'minioadmin'
        networks:
            - mynet
        volumes:
            - minio-data:/data

    patient-service:
        build: .
        restart: always
        image: patient-image:latest
        ports:
            - "9797:9797"
            - "9798:9798"
        networks:
            - mynet

networks:
    mynet:
        driver: bridge

volumes:
    minio-data:
        driver: local
